# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Admin.create([
  { :email => "noj@moovweb.com", :encrypted_password => "$2a$10$aCyoalDPS3YOu5jeovzhz.CF61Wx3BNZ860JWbjwWIlKwk9KnOxs.", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 3, :current_sign_in_at => "2012-09-19 06:04:34", :last_sign_in_at => "2012-09-19 02:09:58", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2012-09-19 01:55:16", :updated_at => "2012-09-19 06:04:34" }
], :without_protection => true )



Match.create([
  { :team1 => 3, :team2 => 4, :round => 1, :winner_next => 5, :winner => 3, :created_at => "2012-09-20 09:58:23", :updated_at => "2012-09-20 10:55:53", :bracket => "serious", :loser_next => 8, :schedule => "2012-09-20 09:57:00" },
  { :team1 => 5, :team2 => 6, :round => 2, :winner_next => 5, :winner => 6, :created_at => "2012-09-20 09:58:49", :updated_at => "2012-09-20 10:56:34", :bracket => "serious", :loser_next => 8, :schedule => "2012-09-20 09:57:00" },
  { :team1 => 7, :team2 => 8, :round => 3, :winner_next => 6, :winner => nil, :created_at => "2012-09-20 09:59:08", :updated_at => "2012-09-20 09:59:08", :bracket => "serious", :loser_next => 9, :schedule => "2012-09-20 09:57:00" },
  { :team1 => 9, :team2 => 10, :round => 4, :winner_next => 6, :winner => nil, :created_at => "2012-09-20 09:59:26", :updated_at => "2012-09-20 09:59:26", :bracket => "serious", :loser_next => 9, :schedule => "2012-09-20 09:57:00" },
  { :team1 => 3, :team2 => 6, :round => 5, :winner_next => 7, :winner => nil, :created_at => "2012-09-20 09:59:49", :updated_at => "2012-09-20 10:56:34", :bracket => "serious", :loser_next => 10, :schedule => "2012-09-20 09:57:00" },
  { :team1 => nil, :team2 => nil, :round => 6, :winner_next => 7, :winner => nil, :created_at => "2012-09-20 10:00:03", :updated_at => "2012-09-20 10:00:03", :bracket => "serious", :loser_next => 11, :schedule => "2012-09-20 09:57:00" },
  { :team1 => nil, :team2 => nil, :round => 7, :winner_next => 14, :winner => nil, :created_at => "2012-09-20 10:00:37", :updated_at => "2012-09-20 10:00:37", :bracket => "serious", :loser_next => 12, :schedule => "2012-09-20 09:57:00" },
  { :team1 => 4, :team2 => 5, :round => 8, :winner_next => 10, :winner => 4, :created_at => "2012-09-20 10:01:10", :updated_at => "2012-09-20 10:56:50", :bracket => "serious_wildcard", :loser_next => nil, :schedule => "2012-09-20 09:57:00" },
  { :team1 => nil, :team2 => nil, :round => 9, :winner_next => 11, :winner => nil, :created_at => "2012-09-20 10:01:23", :updated_at => "2012-09-20 10:01:23", :bracket => "serious_wildcard", :loser_next => nil, :schedule => "2012-09-20 09:57:00" },
  { :team1 => 4, :team2 => nil, :round => 10, :winner_next => 12, :winner => nil, :created_at => "2012-09-20 10:01:37", :updated_at => "2012-09-20 10:56:50", :bracket => "serious_wildcard", :loser_next => nil, :schedule => "2012-09-20 09:57:00" },
  { :team1 => nil, :team2 => nil, :round => 11, :winner_next => 13, :winner => nil, :created_at => "2012-09-20 10:01:50", :updated_at => "2012-09-20 10:01:50", :bracket => "serious_wildcard", :loser_next => nil, :schedule => "2012-09-20 09:57:00" },
  { :team1 => nil, :team2 => nil, :round => 12, :winner_next => 13, :winner => nil, :created_at => "2012-09-20 10:02:00", :updated_at => "2012-09-20 10:02:00", :bracket => "serious_wildcard", :loser_next => nil, :schedule => "2012-09-20 09:57:00" },
  { :team1 => nil, :team2 => nil, :round => 13, :winner_next => 14, :winner => nil, :created_at => "2012-09-20 10:02:12", :updated_at => "2012-09-20 10:02:12", :bracket => "serious_wildcard", :loser_next => nil, :schedule => "2012-09-20 09:57:00" },
  { :team1 => nil, :team2 => nil, :round => 14, :winner_next => nil, :winner => nil, :created_at => "2012-09-20 10:02:24", :updated_at => "2012-09-20 10:02:24", :bracket => "serious_finals", :loser_next => nil, :schedule => "2012-09-20 09:57:00" }
], :without_protection => true )



Team.create([
  { :name => "Manoj", :members => "Manoj", :bio => "skaf", :smack => "fa", :created_at => "2012-09-20 09:49:10", :updated_at => "2012-09-20 09:49:10", :league => "serious", :lose_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/lose.jpg", :win_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/win.jpg", :smack_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/smack.jpg", :emails => "something@stuff.com" },
  { :name => "Hari2", :members => "Hari2", :bio => "adsf", :smack => "asdf", :created_at => "2012-09-20 09:49:47", :updated_at => "2012-09-20 11:26:56", :league => "serious", :lose_img => "http://dl.dropbox.com/u/9921601/moovweb/pingpong/default/lose.jpg", :win_img => "http://dl.dropbox.com/u/9921601/moovweb/pingpong/default/win.jpg", :smack_img => "http://dl.dropbox.com/u/9921601/moovweb/pingpong/default/smack.jpg", :emails => "ha@h.com" },
  { :name => "tarun", :members => "tarun", :bio => "asdf", :smack => "asf", :created_at => "2012-09-20 09:50:24", :updated_at => "2012-09-20 09:50:24", :league => "serious", :lose_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/lose.jpg", :win_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/win.jpg", :smack_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/smack.jpg", :emails => "t@t.com" },
  { :name => "ajay", :members => "ayay", :bio => "asdf", :smack => "asf", :created_at => "2012-09-20 09:50:50", :updated_at => "2012-09-20 09:50:50", :league => "serious", :lose_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/lose.jpg", :win_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/win.jpg", :smack_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/smack.jpg", :emails => "a@j.com" },
  { :name => "sean", :members => "sean", :bio => "asdf", :smack => "asf", :created_at => "2012-09-20 09:51:02", :updated_at => "2012-09-20 09:51:02", :league => "serious", :lose_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/lose.jpg", :win_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/win.jpg", :smack_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/smack.jpg", :emails => "a@j.com" },
  { :name => "mitch", :members => "mitch", :bio => "asdf", :smack => "asf", :created_at => "2012-09-20 09:51:21", :updated_at => "2012-09-20 09:51:21", :league => "serious", :lose_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/lose.jpg", :win_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/win.jpg", :smack_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/smack.jpg", :emails => "a@j.com" },
  { :name => "omar", :members => "omar", :bio => "asdf", :smack => "asf", :created_at => "2012-09-20 09:51:43", :updated_at => "2012-09-20 09:51:43", :league => "serious", :lose_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/lose.jpg", :win_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/win.jpg", :smack_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/smack.jpg", :emails => "a@j.com" },
  { :name => "james", :members => "james", :bio => "asdf", :smack => "asf", :created_at => "2012-09-20 09:51:52", :updated_at => "2012-09-20 09:51:52", :league => "serious", :lose_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/lose.jpg", :win_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/win.jpg", :smack_img => "https://dl.dropbox.com/u/9921601/moovweb/pingpong/default/smack.jpg", :emails => "a@j.com" }
], :without_protection => true )


